use k8s_openapi::api::core::v1::{Node, Pod};
use kube::api::{DynamicObject, TypeMeta};

/// TypeMetaDefaulter performs defaulting of TypeMeta for a given object.
/// This is necessary because the TypeMeta is not always present, especially for
/// a returned list of objects from the API server.
/// 
/// This method is not required to be implemented for all objects, only for DynamicObject,
/// as serde serializes typed objects with TypeMeta generated by k8s-openapi.
pub trait TypeMetaDefaulter {
    fn default_type_meta(&mut self, _type_meta: TypeMeta) {}
}

impl TypeMetaDefaulter for DynamicObject {
    fn default_type_meta(&mut self, type_meta: TypeMeta) {
        self.types.get_or_insert(type_meta);
    }
}

impl TypeMetaDefaulter for Node {}
impl TypeMetaDefaulter for Pod {}
