{{- if .Values.ca_file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crust-gather.caSecretName" . }}
  labels:
    {{- include "crust-gather.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ca.pem: |
{{ .Values.ca_file | nindent 4 }}
{{- end }}
