{{- include "crust-gather.validateOCIAuth" . }}
{{- if or .Values.token .Values.username .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crust-gather.ociAuthSecretName" . }}
  labels:
    {{- include "crust-gather.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.token }}
  OCI_AUTH_TOKEN: {{ .Values.token | quote }}
  {{- else }}
  OCI_AUTH_USERNAME: {{ .Values.username | quote }}
  OCI_AUTH_PASSWORD: {{ .Values.password | quote }}
  {{- end }}
{{- end }}
